import { useState } from 'react';
import { FiEdit2, FiTrash2, FiFolderPlus, FiFolder } from 'react-icons/fi';
import ActionConflictModal from './ActionConflictModal';
import ItemActionsDropdown from './ItemActionsDropdown';
import DriveFolderModal from './DriveFolderModal';

import type { FileType, ImageFolder } from '../api/firestore/types/shared';
import type { Item } from '../api/firestore/services/misc/userItems';
import { useCreateUserItemMutation } from '../api/firestore/firestoreApi';

interface ItemActionsProps {
  isPublicItem: boolean;
  itemData: Item;
  onEdit: () => void;
  onDelete: (itemId: string) => void;
  onImageFolderSelect: ({
    folder,
    files,
  }: {
    folder: ImageFolder;
    files: FileType[];
  }) => void;
  imageFolder?: ImageFolder;
  readonly: boolean;
}

function ItemActions({
  isPublicItem,
  itemData,
  onEdit,
  onDelete,
  onImageFolderSelect,
  imageFolder,
  readonly,
}: ItemActionsProps) {
  const itemId = itemData.id;
  const [showDrivePopup, setShowDrivePopup] = useState(false);

  // Local state container tracking the operational details of the clone/move action
  const [conflictModal, setConflictModal] = useState<{
    isOpen: boolean;
    type: 'move' | 'duplicate';
    targetPublic: boolean;
  }>({ isOpen: false, type: 'move', targetPublic: false });

  const [createItem] = useCreateUserItemMutation();

  // Triggers the functional flow, raising the verification window
  const handleActionTrigger = (
    type: 'move' | 'duplicate',
    targetPublic: boolean
  ) => {
    setConflictModal({ isOpen: true, type, targetPublic });
  };

  // Dispatches actions inside the collection domains after handling modal responses
  const executeAction = async (resolution: 'overwrite' | 'merge') => {
    const { targetPublic, type } = conflictModal;

    // Purge autogenerated document ids and temporal parameters to avoid relational locking
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { id: _, createdAt: __, updatedAt: ___, ...cleanPayload } = itemData;

    try {
      if (resolution === 'overwrite') {
        console.log('payloadl', cleanPayload);
        // Enforces full structural overrides inside target namespaces
        await createItem({
          ...cleanPayload,
          isPublicItem: targetPublic,
        }).unwrap();
      } else if (resolution === 'merge') {
        // Performs partial updates or shallow dictionary merges matching existing document paths
        await createItem({
          ...cleanPayload,
          isPublicItem: targetPublic,
        }).unwrap();
      }

      // If operational lifecycle dictates a full migration, wipe the collection of origin
      if (type === 'move') {
        await onDelete(itemId);
      }
    } catch (error) {
      console.error(`Execution failure during operation: ${type}`, error);
    } finally {
      // Gracefully collapse operational overlays
      setConflictModal((prev) => ({ ...prev, isOpen: false }));
    }
  };

  return (
    <div className="flex gap-2 items-center">
      {/* 1. Modal Interceptor Portal */}
      <ActionConflictModal
        isOpen={conflictModal.isOpen}
        type={conflictModal.type}
        targetPublic={conflictModal.targetPublic}
        onResolve={executeAction}
        onCancel={() =>
          setConflictModal((prev) => ({ ...prev, isOpen: false }))
        }
      />

      {/* 2. DriveBrowser Modal Pipeline */}
      <DriveFolderModal
        isOpen={showDrivePopup}
        selectedFolder={imageFolder}
        onClose={() => setShowDrivePopup(false)}
        onSelectFolder={(data) => {
          onImageFolderSelect({
            folder: data.folder,
            files: data.files,
          });
        }}
      />

      {/* 3. Asset Attachments & Selection */}
      <div className="flex gap-0">
        {imageFolder && (
          <div className="flex items-center gap-1 bg-base-200 rounded py-1 px-1.5 mr-1 max-w-[100px] truncate">
            <span className="text-[10px] opacity-80 truncate">
              {imageFolder.name}
            </span>
          </div>
        )}
        <button
          type="button"
          data-tip="Select Drive folder"
          className="btn btn-sm btn-ghost tooltip"
          onClick={() => setShowDrivePopup(true)}
          disabled={readonly}
        >
          {imageFolder ? (
            <FiFolder
              size={18}
              className={`text-primary ${readonly ? '' : 'fill-current'}`}
            />
          ) : (
            <FiFolderPlus size={18} />
          )}
        </button>
      </div>

      {/* 4. Edit Actions */}
      <button
        type="button"
        className="btn btn-sm btn-ghost tooltip"
        data-tip="Edit name"
        onClick={onEdit}
        disabled={readonly}
      >
        <FiEdit2 size={18} />
      </button>

      {/* 5. Modular Options Wheel Subcomponent */}
      <ItemActionsDropdown
        isPublicItem={isPublicItem}
        onTriggerAction={handleActionTrigger}
        readonly={readonly}
      />

      {/* 6. Destructive Actions Trigger */}
      <button
        type="button"
        className="btn btn-sm btn-ghost btn-error hover:bg-error/10 tooltip"
        data-tip="Delete collectible"
        onClick={() => onDelete(itemId)}
        disabled={readonly}
      >
        <FiTrash2 size={18} />
      </button>
    </div>
  );
}

export default ItemActions;
